/**
 * Digital Business Card Themes Specification — All Light Design
 */

import { CardTemplate, CardTemplateId } from '../models/template';

export const CARD_TEMPLATES: Record<CardTemplateId, CardTemplate> = {
  professional: {
    id: 'professional',
    name: 'Professional',
    description: 'Structured light corporate layout with executive typography and navy/gold accents.',
    style: {
      gradientColors: ['#FFFFFF', '#F8FAFC', '#F1F5F9'],
      textColor: '#0F172A',
      subtextColor: '#475569',
      accentColor: '#1E3A8A',
      cardBackground: '#FFFFFF',
      borderColor: '#E2E8F0',
      badgeBackground: '#EFF6FF',
      chipBackground: '#F8FAFC',
      isDark: false,
    },
    qrtracTemplateId: '4',
    tags: ['corporate', 'executive', 'structured'],
  },
  modern: {
    id: 'modern',
    name: 'Modern',
    description: 'Dynamic light tech layout with centered hero avatar and electric cyan accents.',
    style: {
      gradientColors: ['#FFFFFF', '#F0F9FF', '#E0F2FE'],
      textColor: '#0F172A',
      subtextColor: '#0284C7',
      accentColor: '#0284C7',
      cardBackground: '#FFFFFF',
      borderColor: '#BAE6FD',
      badgeBackground: '#E0F2FE',
      chipBackground: '#F0F9FF',
      isDark: false,
    },
    qrtracTemplateId: '1',
    tags: ['modern', 'tech', 'dynamic'],
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Simple light minimalist layout with generous whitespace and razor-sharp charcoal typography.',
    style: {
      gradientColors: ['#FFFFFF', '#FAFAFA', '#F4F4F5'],
      textColor: '#111827',
      subtextColor: '#6B7280',
      accentColor: '#111827',
      cardBackground: '#FFFFFF',
      borderColor: '#E5E7EB',
      badgeBackground: '#F9FAFB',
      chipBackground: '#F9FAFB',
      isDark: false,
    },
    qrtracTemplateId: '1',
    tags: ['minimal', 'clean', 'simple'],
  },
  // Legacy aliases
  corporate_executive: {
    id: 'corporate_executive',
    name: 'Corporate Executive',
    description: 'Legacy alias for Professional template.',
    style: {
      gradientColors: ['#FFFFFF', '#F8FAFC', '#F1F5F9'],
      textColor: '#0F172A',
      subtextColor: '#475569',
      accentColor: '#1E3A8A',
      cardBackground: '#FFFFFF',
      borderColor: '#E2E8F0',
      badgeBackground: '#EFF6FF',
      chipBackground: '#F8FAFC',
      isDark: false,
    },
    qrtracTemplateId: '4',
    tags: ['corporate', 'executive'],
  },
  modern_minimal: {
    id: 'modern_minimal',
    name: 'Modern Minimal',
    description: 'Legacy alias for Modern template.',
    style: {
      gradientColors: ['#FFFFFF', '#F0F9FF', '#E0F2FE'],
      textColor: '#0F172A',
      subtextColor: '#0284C7',
      accentColor: '#0284C7',
      cardBackground: '#FFFFFF',
      borderColor: '#BAE6FD',
      badgeBackground: '#E0F2FE',
      chipBackground: '#F0F9FF',
      isDark: false,
    },
    qrtracTemplateId: '1',
    tags: ['modern', 'tech'],
  },
  minimal_mono: {
    id: 'minimal_mono',
    name: 'Minimal Mono',
    description: 'Legacy alias for Minimal template.',
    style: {
      gradientColors: ['#FFFFFF', '#FAFAFA', '#F4F4F5'],
      textColor: '#111827',
      subtextColor: '#6B7280',
      accentColor: '#111827',
      cardBackground: '#FFFFFF',
      borderColor: '#E5E7EB',
      badgeBackground: '#F9FAFB',
      chipBackground: '#F9FAFB',
      isDark: false,
    },
    qrtracTemplateId: '1',
    tags: ['minimal', 'clean'],
  },
  vibrant_glass: {
    id: 'vibrant_glass',
    name: 'Vibrant Glass',
    description: 'Legacy alias for Vibrant style.',
    style: {
      gradientColors: ['#FFFFFF', '#FAF5FF', '#F3E8FF'],
      textColor: '#0F172A',
      subtextColor: '#7C3AED',
      accentColor: '#7C3AED',
      cardBackground: '#FFFFFF',
      borderColor: '#DDD6FE',
      badgeBackground: '#EDE9FE',
      chipBackground: '#F5F3FF',
      isDark: false,
    },
    qrtracTemplateId: '2',
    tags: ['vibrant'],
  },
  creative_designer: {
    id: 'creative_designer',
    name: 'Creative Designer',
    description: 'Legacy alias for Creative style.',
    style: {
      gradientColors: ['#FFFFFF', '#FFF7ED', '#FFEDD5'],
      textColor: '#0F172A',
      subtextColor: '#EA580C',
      accentColor: '#EA580C',
      cardBackground: '#FFFFFF',
      borderColor: '#FED7AA',
      badgeBackground: '#FFEDD5',
      chipBackground: '#FFF7ED',
      isDark: false,
    },
    qrtracTemplateId: '3',
    tags: ['creative'],
  },
};

export const CARD_TEMPLATE_LIST: CardTemplate[] = [
  CARD_TEMPLATES.professional,
  CARD_TEMPLATES.modern,
  CARD_TEMPLATES.minimal,
];
