/**
 * Business Card Application Domain Model
 * Designed with a strict separation between internal UI presentation state
 * and QRTRAC API cloud mapping properties.
 */

import { CardContact } from './contact';
import { SocialLink } from './social';
import { CardTemplateId } from './template';

/**
 * QRTRAC Cloud-Specific Metadata & Mappings
 */
export interface QrTracCloudMetadata {
  qrtracId?: string; // QR code ID generated by QRTRAC API
  displayId?: string; // Custom short slug (e.g., qrtrac.me/my-card)
  teamId?: string; // QRTRAC team context
  qrImageUrl?: string; // Hosted QR image URL from QRTRAC CDN
  qrImageHash?: string; // Hash verification string
  publicUrl?: string; // Public short redirect URL
  templateId?: string; // QR design template ID from QRTRAC
  batchId?: string; // Batch identifier if generated in bulk
  isSynced: boolean; // Flag indicating if synced with QRTRAC cloud
  lastSyncedAt?: number;
}

/**
 * Scan & Lead Analytics Summary (from QRTRAC Telemetry)
 */
export interface CardAnalyticsSummary {
  totalScans: number;
  todayScans: number;
  yesterdayScans: number;
  totalLeads?: number;
  lastScannedAt?: number;
}

/**
 * Core Application Digital Business Card Model
 */
export interface BusinessCard {
  // Application / UI Identity
  id: string; // Unique local/app UUID
  name: string; // Card display title (e.g. "Alex Morgan • Tech Lead")
  profilePhoto?: string; // Local URI or hosted image URL

  // Contact Information
  contact: CardContact;

  // Social & Online Presence
  socialLinks: SocialLink[];

  // Visual Presentation Theme (Local UI Layout)
  template: CardTemplateId;

  // User Preferences & State
  isFavorite: boolean;
  tags: string[];

  // QRTRAC Cloud Integration Properties (Separated Layer)
  cloud: QrTracCloudMetadata;

  // Scan Telemetry Summary
  analytics: CardAnalyticsSummary;

  // Timestamps
  createdAt: number;
  updatedAt: number;
}

/**
 * Draft/Editor Form State for creating or editing a card
 */
export interface CardEditorDraft {
  id?: string;
  name: string;
  firstName: string;
  lastName: string;
  designation: string;
  company: string;
  phoneMobile: string;
  phoneWork: string;
  email: string;
  website: string;
  street: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  bio: string;
  notes: string;
  profilePhoto?: string;
  template: CardTemplateId;
  displayId: string;
  qrtracTemplateId?: string;
  socialLinks: SocialLink[];
  tags: string[];
}
